### ISSUE TITLE
Combat tweaks

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#10]
- [x] Remove or greatly reduce screen shake on all weapons
- [x] RPG has no killer name in kill feed
- [x] Remove team killing
- [x] Player outlines should only exist on enemies and should be red

**Comment by ShadowBrian** [comment]
This might fit here, the flag needs a more clear return cycle, part of it is particle work but some of it might also be UI work for conveying how far along the flag is to respawning and this being a little bar would also show it returning faster when you're in the flag's return zone.

**Comment by ShadowBrian** [comment]
Allow class switching and maybe have dynamic class caps based on people's selections but I'm guessing that was already planned and just not finished
