### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#12]
- [x] New name tags (component-based)
- [x] Hitmarkers don't show correctly on some clients
- [x] Flag icons on compass always display even if flag is not home
- [x] Better chat
- [x] Damage indicators
- [x] Icons for metal blocks are always blue
- [x] Re-work kill feed
- [x] Need some indicator to show whether flag is home or not
- [ ] #48 
  - [ ] Should hook into an XP system

**Comment by ShadowBrian** [comment]
This is a minor one but maybe rework chat a little, at least giving people their team colors on their names in chat

**Comment by xezno** [comment]
Added

**Comment by ShadowBrian** [comment]
Multiple people have had issues with UI flickering, it's visible in this https://www.youtube.com/watch?v=4RsbNPE6saA video
