### ISSUE TITLE
Multiple people have had issues with UI flickering

### ISSUE THREAD

**Issue by ShadowBrian** [apetavern/sbox-fortwars#19]
Multiple people have had issues with UI flickering, it's visible in this https://www.youtube.com/watch?v=4RsbNPE6saA video

_Originally posted by @ShadowBrian in https://github.com/apetavern/sbox-fortwars/issues/12#issuecomment-1036732468_

![Discord_2022-02-12_00-08-52](https://user-images.githubusercontent.com/11138884/153682806-b4d58fad-1443-4a76-951a-7cc37a456b08.png)

**Comment by xezno** [comment]
I don't know what causes this and everyone seems to have had a different flickering experience, so I can't really do much about this right now
