### ISSUE TITLE
UI: Options menu

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#30]
- [ ] Crosshair customization
- [ ] Togglable aiming down sights
- [ ] Aiming sensitivity multiplier
- [ ] Camera field of view

**Comment by ShadowBrian** [comment]
I think aiming sensitivity is actually a S&Box native setting but perhaps how much it gets affected while scoping I guess would make sense

**Comment by xezno** [comment]
Closing as this is out of scope right now
