### ISSUE TITLE
Feedback: 25/02 Playtest

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#34]
- [x] Repair tool has NRE
- [x] Bog roll weapon is broken (needs a refactor): https://cdn.discordapp.com/attachments/940984234124922900/946869114767564830/2022-02-25_14-39-32.mp4
- [ ] #49
  - [x] Fallback doesn't work either: the fallback texture is in the wrong place - should be in the UI textures folder
- [x] Glows only render when around 256 units away or nearer; should be much further
- [x] Muzzle flashes are missing textures

**Comment by trundler-dev** [comment]
- [ ] Switching classes outside of spawn should count as a death

**Comment by ShadowBrian** [comment]
- [ ] Sometimes reload animations play twice when firing right after a reload
