### ISSUE TITLE
UI: Sniper scope bug

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#49]
Sniper scope doesn't work right: performance is bad, HUD flickers, weapon renders in scene when it shouldn't

**Comment by gvarados1** [comment]
is this included in this issue?
![20220331225726_1](https://user-images.githubusercontent.com/39461072/161192277-3f42797f-d5d4-43cc-b1ce-b73d5401ab71.jpg)

**Comment by xezno** [comment]
Removing this from the full release milestone because it's relatively low-priority right now

**Comment by xezno** [comment]
Going to look at re-implementing the cooler scope shader now that we have more control over rendering
