### ISSUE TITLE
Titans map tweaks

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#9]
- [ ] Get rid of the gaps between the two sides (where the wall is)
- [ ] Fix the weird stuff you bump into near bases (widen the path a bit)
- [ ] Increase wall collision height so that people can't build over it (might need to add a clip to the top of the entire level?)

**Comment by trundler-dev** [comment]
Since gumby is burnt out from mapping and has left Ape Tavern (and the map was subsequently removed from the pool), I am closing this.
